package modeloBD;
// Generated 27-jun-2018 10:59:07 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cita generated by hbm2java
 */
@Entity
@Table(name = "cita", catalog = "bilnow_db")
public class Cita implements java.io.Serializable {

	private Integer idCita;
	private Date fechaCita;
	private String idMascota;

	public Cita() {
	}

	public Cita(Date fechaCita, String idMascota) {
		this.fechaCita = fechaCita;
		this.idMascota = idMascota;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_Cita", unique = true, nullable = false)
	public Integer getIdCita() {
		return this.idCita;
	}

	public void setIdCita(Integer idCita) {
		this.idCita = idCita;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_Cita", nullable = false, length = 10)
	public Date getFechaCita() {
		return this.fechaCita;
	}

	public void setFechaCita(Date fechaCita) {
		this.fechaCita = fechaCita;
	}

	@Column(name = "id_Mascota", nullable = false, length = 15)
	public String getIdMascota() {
		return this.idMascota;
	}

	public void setIdMascota(String idMascota) {
		this.idMascota = idMascota;
	}

}
