package modeloBD;
// Generated 27-jun-2018 10:59:07 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mascota generated by hbm2java
 */
@Entity
@Table(name = "mascota", catalog = "bilnow_db")
public class Mascota implements java.io.Serializable {

	private String idMascota;
	private String nombreMascota;
	private String espMascota;
	private String razaMascota;
	private String capaMascota;
	private Date fechaNacimiento;
	private boolean sexoMascota;
	private String idDuenio;

	public Mascota() {
	}

	public Mascota(String idMascota, String nombreMascota, String espMascota, String razaMascota, String capaMascota,
			Date fechaNacimiento, boolean sexoMascota, String idDuenio) {
		this.idMascota = idMascota;
		this.nombreMascota = nombreMascota;
		this.espMascota = espMascota;
		this.razaMascota = razaMascota;
		this.capaMascota = capaMascota;
		this.fechaNacimiento = fechaNacimiento;
		this.sexoMascota = sexoMascota;
		this.idDuenio = idDuenio;
	}

	@Id

	@Column(name = "id_Mascota", unique = true, nullable = false, length = 15)
	public String getIdMascota() {
		return this.idMascota;
	}

	public void setIdMascota(String idMascota) {
		this.idMascota = idMascota;
	}

	@Column(name = "nombre_Mascota", nullable = false, length = 7)
	public String getNombreMascota() {
		return this.nombreMascota;
	}

	public void setNombreMascota(String nombreMascota) {
		this.nombreMascota = nombreMascota;
	}

	@Column(name = "esp_Mascota", nullable = false, length = 10)
	public String getEspMascota() {
		return this.espMascota;
	}

	public void setEspMascota(String espMascota) {
		this.espMascota = espMascota;
	}

	@Column(name = "raza_Mascota", nullable = false, length = 10)
	public String getRazaMascota() {
		return this.razaMascota;
	}

	public void setRazaMascota(String razaMascota) {
		this.razaMascota = razaMascota;
	}

	@Column(name = "capa_Mascota", nullable = false, length = 10)
	public String getCapaMascota() {
		return this.capaMascota;
	}

	public void setCapaMascota(String capaMascota) {
		this.capaMascota = capaMascota;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_Nacimiento", nullable = false, length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "sexo_Mascota", nullable = false)
	public boolean isSexoMascota() {
		return this.sexoMascota;
	}

	public void setSexoMascota(boolean sexoMascota) {
		this.sexoMascota = sexoMascota;
	}

	@Column(name = "id_Duenio", nullable = false, length = 9)
	public String getIdDuenio() {
		return this.idDuenio;
	}

	public void setIdDuenio(String idDuenio) {
		this.idDuenio = idDuenio;
	}

}
