package modeloBD;
// Generated 27-jun-2018 13:23:48 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Productosreservados generated by hbm2java
 */
@Entity
@Table(name = "productosreservados", catalog = "bilnow_db")
public class Productosreservados implements java.io.Serializable {

	private int idReserva;
	private int idProducto;

	public Productosreservados() {
	}

	public Productosreservados(int idReserva, int idProducto) {
		this.idReserva = idReserva;
		this.idProducto = idProducto;
	}

	@Id

	@Column(name = "id_Reserva", unique = true, nullable = false)
	public int getIdReserva() {
		return this.idReserva;
	}

	public void setIdReserva(int idReserva) {
		this.idReserva = idReserva;
	}

	@Column(name = "id_Producto", nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

}
