package modeloBD;
// Generated 27-jun-2018 13:23:48 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name = "reserva", catalog = "bilnow_db")
public class Reserva implements java.io.Serializable {

	private Integer idReserva;
	private String idUsuario;
	private boolean pedidoRecogido;

	public Reserva() {
	}

	public Reserva(String idUsuario, boolean pedidoRecogido) {
		this.idUsuario = idUsuario;
		this.pedidoRecogido = pedidoRecogido;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_Reserva", unique = true, nullable = false)
	public Integer getIdReserva() {
		return this.idReserva;
	}

	public void setIdReserva(Integer idReserva) {
		this.idReserva = idReserva;
	}

	@Column(name = "id_Usuario", nullable = false, length = 9)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "pedido_Recogido", nullable = false)
	public boolean isPedidoRecogido() {
		return this.pedidoRecogido;
	}

	public void setPedidoRecogido(boolean pedidoRecogido) {
		this.pedidoRecogido = pedidoRecogido;
	}

}
